Tasks/task1
alexander-chuchko/altexsoft-lab-2020 pull request #1
Opened 2020-08-04 16:42 UTC by alexander-chuchko

Александр, здравствуйте! Я проект загрузил в GitHub 02.08.20 (т.е. в срок), но как оказалось не до конца все выполнил. Сомнения начались из-за отсутствия каких либо действий на моем профиле. Вот сегодня проверил и обнаружил свою недоработку, после чего закачал проект в соответствии с Вашими требованиями (как мне видеться)). Извините за задержку.

2020-08-04 19:01 UTC, alex-geraschenko commented on Texteditor/App.config
> +        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
Курс по **.NET Core**

2020-08-04 19:02 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +                Console.WriteLine("\n\tFile this name is not!!!\n");
Стоит подтянуть английский. Или хотя бы воспользуйтесь Гугл переводчиком

2020-08-04 19:03 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +                string[] separators = { ",", ".", "!", "?", ":", ";", " ", "\n", "\r", "(", ")", "\"" };
Обратите внимание на регулярные выражения

2020-08-04 19:04 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +                    //Выполняем проверку строк на содержание числовых значений. Цифровые значения, я не считаю словом
> Цифровые значения, я не считаю словом

А MS Word считает

2020-08-04 19:04 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +                        Console.WriteLine(allstrings[i - 1].ToString() + ", ");
Обратите внимание на `string.Join`

2020-08-04 19:05 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +                string[] separ = { ",", "!", "?", ":", ";", " " };
Обратите внимание на регулярные выражения

2020-08-04 19:08 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +            //Создаем экземпляр класса FileInfo
Это задание можно сделать гораздо проще

2020-08-04 19:31 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +                    //Выполняем проверку строк на содержание числовых значений. Цифровые значения, я не считаю словом
Я предварительно проверил в редакторах и в том числе  MS Word, но заказчик не уточнил это в ТЗ. И я подумал, что в друг эта программа необходима для переводчиков (заказчик/исполнитель). Цифры нет необходимости переводить, а значит и учитывать в кол-ве переведенных слов. Вообщем это сделано осознано))

2020-08-04 19:53 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +                    //Выполняем проверку строк на содержание числовых значений. Цифровые значения, я не считаю словом
Если что-то не уточнено в ТЗ, то имеет смысл спросить в чате телеграмм (который создан в том числе и для таких вопросов). Тем более, что там этот вопрос поднимался и на него есть ответ. Это называется - уточнение/выяснение требований.
Если вы во время работы с клиентом тоже будете додумывать за него, то мало каким клиентам это понравится.

2020-08-05 19:34 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +                    //Выполняем проверку строк на содержание числовых значений. Цифровые значения, я не считаю словом
Понял. Получается в тех местах, где Вы оставили комментарии, необходимо доработать код и после этого двигаться дальше (если будет одобрение)

2020-08-07 13:44 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +                    //Выполняем проверку строк на содержание числовых значений. Цифровые значения, я не считаю словом
да

2020-08-09 13:48 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +                string[] separators = { ",", ".", "!", "?", ":", ";", " ", "\n", "\r", "(", ")", "\"" };
Исправил код. Применил регулярные выражения. Действительно мощная технология! И я так понимаю, что особенно важна в Web направлении.

2020-08-09 13:49 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +                    //Выполняем проверку строк на содержание числовых значений. Цифровые значения, я не считаю словом
Исправил код

2020-08-09 13:49 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +                        Console.WriteLine(allstrings[i - 1].ToString() + ", ");
Применил string.Join

2020-08-09 13:49 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +                string[] separ = { ",", "!", "?", ":", ";", " " };
Исправил код

2020-08-09 13:50 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +            //Создаем экземпляр класса FileInfo
Рефакторинг задания выполнен

2020-08-09 13:51 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +                    //Выполняем проверку строк на содержание числовых значений. Цифровые значения, я не считаю словом
Считает слова в соответствии с  MS Word

2020-08-09 13:52 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +                Console.WriteLine("\n\tFile this name is not!!!\n");
Сейчас работаем в этом направлении

2020-08-12 15:08 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +﻿#if true
Зачем это?

2020-08-12 15:08 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +            if (dir.GetDirectories().Length > 0)
`GetDirectories` дублируется

2020-08-12 15:10 UTC, alex-geraschenko commented on Texteditor/Program.cs
> +            string path = @System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + "\\" + namefile;
Файл должен задаваться из консоли

2020-08-30 13:18 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +            string path = @System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + "\\" + namefile;
Все замечания учтены. Проект отправил на ревью

2020-08-30 13:48 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +            if (dir.GetDirectories().Length > 0)
Исправил

2020-08-30 13:55 UTC, alexander-chuchko commented on Texteditor/Program.cs
> +            string path = @System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + "\\" + namefile;
Честно признаться, много времени занимает GIt. Может даже больше, чем выполнение заданий). Хочется разобраться, как он работает и устроен изнутри. А он (Git) не такой простой, как показалось на первый взгляд или может быть просто опыта в использовании не было (до курсов).

2020-08-31 10:07 UTC, alex-geraschenko requested changes

2020-08-31 10:07 UTC, alex-geraschenko commented on Texteditor/PathUser.cs
> +            if (path == null || path == string.Empty)
Используйте `string.IsNullOrEmpty`

2020-08-31 16:33 UTC, alexander-chuchko commented on Texteditor/PathUser.cs
> +            if (path == null || path == string.Empty)
Исправил. Я и хотел применить этот метод и часто раньше применял, что сбило с толку.

2020-08-31 16:39 UTC, alexander-chuchko commented on Texteditor/PathUser.cs
> +            if (path == null || path == string.Empty)
Я вот видел в переписке один из участников в группе Telegram спрашивал на счет выражения var a=new int(); Это же синтаксический сахар. Вы бы порекомендовали в своих проектах применять такого типа выражения или нет?

2020-08-31 18:21 UTC, alex-geraschenko requested changes
1. Имена классов, методов, свойств должны быть в `PascalCase`.
2. Имена полей классов, локальных переменных, параметров методов должны быть в `camelCase`

2020-08-31 18:21 UTC, alex-geraschenko commented on Texteditor/Counter.cs
> +        public void ItemWord(Counter obj)
1. Имя метода должно быть в глагольной форме
2. Зачем передавать экземпляр `Counter` внутрь метода `Counter`?

2020-08-31 18:21 UTC, alex-geraschenko commented on Texteditor/Counter.cs
> +                Regex TitleRegex = new Regex(@"[^\'\w\s]", RegexOptions.IgnoreCase);
Локальные переменные надо называть в `camelCase`

2020-08-31 18:21 UTC, alex-geraschenko commented on Texteditor/FileData.cs
> +    public class FileData
Базовый класс лучше делать абстрактным

2020-08-31 18:21 UTC, alex-geraschenko commented on Texteditor/FileData.cs
> +        public bool IsExistenceСheckFile()
Проверьте имя метода, чтобы там не было символов кирилицы

2020-08-31 19:04 UTC, alexander-chuchko commented on Texteditor/Counter.cs
> +        public void ItemWord(Counter obj)
Это обязательно к исполнению? К примеру у меня такой вариант решения. Их может быть сотни. Или так категорически нельзя делать?

2020-08-31 19:04 UTC, alexander-chuchko commented on Texteditor/Counter.cs
> +        public void ItemWord(Counter obj)
вопрос к пункту 2

2020-08-31 19:58 UTC, alexander-chuchko commented on Texteditor/FileData.cs
> +    public class FileData
В данном случае, я не совсем понимаю преимущество абстрактного класса. Только потому что нельзя создать экземпляр класса? Но абстрактный класс должен содержать в обязательном порядке абстрактный метод, который мы должны переопределить в классах наследниках. Но в самом начале было замечание было о том, что необходимо вынести повторяющийся код из классов в родительский класс. Объясните пожалуйста?)

2020-08-31 20:16 UTC, alexander-chuchko commented on Texteditor/FileData.cs
> +    public class FileData
Все исправил. Отправил на ревью. Конечно хотелось бы получать все замечания сразу, а не порциями. Но наверно такое не осуществимо в рамках данного курса!?

2020-09-01 08:25 UTC, alex-geraschenko commented on Texteditor/PathUser.cs
> +            if (path == null || path == string.Empty)
В своей практике я не сталкивался с необходимостью в конструкции `var a = new int()`. Всегда есть проще варианты записи. Поэтому такую конструкцию я бы не рекомендовал в общем случае.

2020-09-01 08:28 UTC, alex-geraschenko commented on Texteditor/FileData.cs
> +    public class FileData
Я бы с радостью, но Вы в одном коммите одно чините, а другое ломаете. Я говорил, что все имена методов должны быть глаголами, а Вы даже те, которые были названы правильно, зачем-то переименовали в существительные.  Например, `WordReversal`

2020-09-01 08:29 UTC, alex-geraschenko commented
Не все комментарии исправлены

2020-09-01 15:02 UTC, alexander-chuchko commented on Texteditor/FileData.cs
> +    public class FileData
Во время обучения в шаге преподаватели как-то не обращали внимания на названия, а больше смотрели на реализацию (логику). Отсюда и вытекают  последствия. Но теперь я точно запомню))

2020-09-01 15:35 UTC, alexander-chuchko commented on Texteditor/FileData.cs
> +    public class FileData
Отправил повторно проект на ревью

2020-09-01 16:39 UTC, alex-geraschenko commented on Texteditor/FileData.cs
> +    public class FileData
> Во время обучения в шаге преподаватели как-то не обращали внимания на названия, а больше смотрели на реализацию (логику)

Такой подход тоже имеет право на жизнь. Если проверять только логику, то это будет похоже на решение академических задачек. Я же стараюсь создать условия, приближенные к реальным проектам. Т.к. большая часть времени при работе над проектом проходит за чтением кода, а не его написаним, то именование играет далеко не последнюю роль.

2020-09-01 16:44 UTC, alex-geraschenko approved these changes
В целом хорошо, можно мержить

2020-09-01 16:44 UTC, alex-geraschenko commented on Texteditor/Counter.cs
> +            this.fileInfo = new FileInfo(path);
Эту инициализацию можно вынести в конструктор базового класса, тогда конструктор наследника будет выглядеть примерно так:
```
public Counter(string path) : base(path)
{
}
```

2020-09-01 16:47 UTC, alexander-chuchko commented on Texteditor/Counter.cs
> +            this.fileInfo = new FileInfo(path);
Я с начала так и сделал с помощью ключевого слова base, а потом решил переиначить.  Спасибо за совет!

2020-09-01 16:49 UTC, merged