Tasks/task3
alexander-chuchko/altexsoft-lab-2020 pull request #3
Opened 2020-10-01 21:22 UTC by alexander-chuchko

2020-10-06 09:35 UTC, alex-geraschenko requested changes
Не нужно удалять файлы из предыдущих заданий! Они должны быть разложены по разным папкам

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/1_CreateIngredients.sql
> +NameIngredient nvarchar(128) not null Unique
Имя поля `NameIngredient` избыточно. Достаточно `Name`, т.к. это поле уже принадлежит `Ingredients`

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/2_CreateCategories.sql
> +NameCategory nvarchar(256) not null Unique
Имя поля `NameCategory` избыточно. Достаточно `Name`, т.к. это поле уже принадлежит `Categories`

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/3_CreateSteps.sql
> +StepName nvarchar(1024) not null
Имя поля `StepName` избыточно. Достаточно `Name`, т.к. это поле уже принадлежит `Steps`

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/4_CreateRecipes.sql
> +RecipeName nvarchar(128) not null Unique,
Имя поля `RecipeName` избыточно. Достаточно `Name`, т.к. это поле уже принадлежит `Recipes`

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/4_CreateRecipes.sql
> +RecipeDescription nvarchar(2048) not null,
Имя поля `RecipeDescription` избыточно. Достаточно `Description`, т.к. это поле уже принадлежит `Recipes`

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/4_CreateRecipes.sql
> +NameCategoryId int foreign key(NameCategoryId) references Categories(id)
Это поле содержит `Name` или `CategoryId` ?

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/5_CreateRecipeIngredient.sql
> +	id int not null identity(1,1) primary key,
Поле `id` избыточно. Достаточно сделать составной первичный ключ из (`RecipeId`, `IngredientId`)

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/6_CreateRecipeStep.sql
> +	id int not null identity(1,1) primary key,
Поле `id` избыточно. Достаточно сделать составной первичный ключ из (`RecipeId`, `StepId`)

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/6_CreateRecipeStep.sql
> +--������� ������� RecipeStep
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/5_CreateRecipeIngredient.sql
> +--������� ������� RecipeIngredient
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/4_CreateRecipes.sql
> +--������� ������� � ���������
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/3_CreateSteps.sql
> +--������� ������� � ���� ������������� ��������
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/2_CreateCategories.sql
> +--������� ������� � �����������
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/1_CreateIngredients.sql
> +--������� ������� � �������������--
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2.sln
>  # Visual Studio 15
Этого файла в третьем задании быть не должно

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/2_data/2_InsertIngredients.sql
> +--������� ������ ��� ��������� � ������� Ingredients--
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/2_data/1_InsertCategories.sql
> +--������� ������ �� ���������� �������� Categories
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/2_data/5_InsertRecipeIngredient.sql
> +--��������� ������� RecipeIngredient
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/2_data/6_InsertRecipeStep.sql
> +--��������� ������� RecipeStep
Неправильная кодировка файла

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/Database2.sqlproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Этого файла в третьем задании быть не должно

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/1_schema/2_CreateCategories.sql
> +NameCategory nvarchar(256) not null Unique
Эта структура не учитывает подкатегорий. https://stackoverflow.com/questions/9409021/id-parentid-list-to-hierarchical-list

2020-10-06 09:35 UTC, alex-geraschenko commented on Database2/Database2/3_queries/ChooseFrom3CategoriesFirstThreeRecipes.sql
> +where Recipes.NameCategoryId=3)
Этот запрос не учитывает подкатегорий. Обратите внимание на **Common Table Expressions**

2020-10-06 12:45 UTC, alexander-chuchko commented on Database2/Database2/1_schema/2_CreateCategories.sql
> +NameCategory nvarchar(256) not null Unique
Разве по условиям 2 и 3 задания подкатегории реализовывать обязательно? я выполни 2 задание без подкатегорий, а 3 выполнил на базе 2 задания

2020-10-06 16:41 UTC, alex-geraschenko commented on Database2/Database2/1_schema/2_CreateCategories.sql
> +NameCategory nvarchar(256) not null Unique
Я Вам и во втором задании оставил комментарий, что нужно реализовать и под категории

2020-10-07 09:50 UTC, alexander-chuchko commented on Database2/Database2/1_schema/2_CreateCategories.sql
> +NameCategory nvarchar(256) not null Unique
до понедельника время есть сдать 2, 3, 4 задания? не успеваю, нужно посещать работу также, и к сожалению пока не связано с программированием, но очень хотелось бы продолжить обучение, т.к. в сравнении с обучением в ШАГе эти курсы гораздо продуктивнее и интереснее

2020-10-27 19:22 UTC, alex-geraschenko requested changes

2020-10-27 19:22 UTC, alex-geraschenko commented on Database/Database/1_schema/2_CreateCategories.sql
> +Name nvarchar(256) not null Unique
Не хватает поля `ParentId` для организации древовидной структуры. https://stackoverflow.com/questions/9409021/id-parentid-list-to-hierarchical-list

2020-10-27 19:22 UTC, alex-geraschenko commented on Database/Database/1_schema/5_CreateRecipes.sql
> +SubcategoryID int foreign key(SubcategoryID) references Subcategory(id)
Поле `SubcategoryID` лишнее

2020-10-27 19:22 UTC, alex-geraschenko commented on Database/Database/1_schema/4_CreateSubcategory.sql
> +create table Subcategory
В этой таблице нет смысла если организовать древовидную структуру в таблице `Categories`

2020-11-05 17:50 UTC, alex-geraschenko requested changes

2020-11-05 17:50 UTC, alex-geraschenko commented on Database/Database/3_queries/ChooseFrom3CategoriesFirstThreeRecipes.sql
> +WITH SelectedId(RecipesId) AS
Вы не до конца разобрались с **Common Table Expressions**. Вам нужны рекурсивные CTE и только для `Categories`

2020-11-10 12:29 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-11-25 19:05 UTC, merged